name: place holder steps
on: workflow_dispatch
# on:
#   push:
#     branches: [ master ]

env:
  IMGTAG: latest

jobs:

  infrastructure:
    runs-on: self-hosted

    steps:
      - name: Infrastructure
        run: echo "Infrastructure Deployment"

  build:
    runs-on: ubuntu-latest
    needs: infrastructure
    permissions:
      id-token: write
      contents: read    
    steps:
    - name: Configure AWS Credentials
      run: echo "AWS Credentials configured"

    - uses: actions/checkout@v1

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: gh-actions-test-repo
        IMAGE_TAG: ${{ github.sha }}
      run: echo "Build Image Completed"


  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Publish Image
        run: echo "Publish Image to ECR"
    
  deploy:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Deploy Service in EKS
        run: echo "Deploy Service in EKS"
        
  tests:
    runs-on: ubuntu-latest
    needs:  deploy
    steps:
      - name: Run Tests
        run: echo "Run Tests"

  report:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Report
        run: echo "Report to Slack Channel"
